spring:
  profiles.active: local
  application:
    name: SaleListener
    version: prod.1.0.0

web:
  socket.client: ${WEB_SOCKET_CLIENT}

server:
  port: 8082

kafka:
  producer:
    client-id: sale-producer
  admin:
    client-id: sale-backend
  bootstrap-server: ${KAFKA_BOOTSTRAP_SERVER}

---
spring:
  profiles: local

web:
  socket.client: http://localhost:8083

kafka:
  bootstrap-server: localhost:9092